# Generated by Django 4.2.7 on 2025-06-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
    ]
