# Generated by Django 4.2.7 on 2025-06-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_commissionslab_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_l1', 'Admin Level 1'), ('admin_l2', 'Admin Level 2'), ('admin_l3', 'Admin Level 3'), ('cp', 'Channel Partner'), ('vp', 'Vice Partner'), ('rm', 'Relationship Manager'), ('team_head', 'Team Head'), ('team_leader', 'Team Leader'), ('branch', 'Branch Manager'), ('commission_admin', 'Commission Admin')], default='cp', max_length=20),
        ),
    ]
